# Generated by Django 5.2.8 on 2025-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="The member's full legal name.", max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('email', models.EmailField(help_text='Must be unique. Used for member login/contact.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('has_father_confessor', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Has a Father Confessor?')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Member',
                'verbose_name_plural': 'Church Members',
                'ordering': ['full_name'],
            },
        ),
    ]
